version: "3"

services:
  photto-enahnce:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              